# https://github.com/elastic/kibana-docker
# FROM docker.elastic.co/kibana/kibana:5.5.1
FROM registry.cn-hangzhou.aliyuncs.com/zicjin/kibana

# Add your kibana plugins setup here
# Example: RUN kibana-plugin install <name|url>
