# https://github.com/elastic/logstash-docker
# FROM docker.elastic.co/logstash/logstash:5.5.1
FROM registry.cn-hangzhou.aliyuncs.com/zicjin/logstash

# Add your logstash plugins setup here
# Example: RUN logstash-plugin install logstash-filter-json
# RUN logstash-plugin install logstash-filter-json
RUN logstash-plugin install logstash-codec-json
